# Generated by Django 2.2.1 on 2019-05-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_cadastro',
        ),
    ]
