# Generated by Django 2.2.1 on 2019-05-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_remove_produto_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(null=True),
        ),
    ]
