# Generated by Django 2.2 on 2019-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desc', models.CharField(max_length=120, unique=True)),
                ('data_in', models.DateField(null=True)),
            ],
            options={
                'db_table': 'book',
                'ordering': ('name',),
            },
        ),
    ]
